language: ruby
rvm:
  - 2.2.1
branches:
  only:
    - master
    - develop
script: bundle exec rspec --tag ~broken_in_ci
install:
  - bundle install --jobs=3 --retry=3
  - bundle exec sqlite3 --version
  - bundle exec rake config
addons:
  code_climate:
    repo_token: ce328d44d99a09d03c1dac2198c731dc8bfd22374fefc1917ce528b25a06ec4e
notifications:
  slack:
    secure: >
      tBgfhb2PJNY+ZW0m1PUc+RnZKfblz4YxjQu7YAFyccTPNjrwKyWcVCGxFZi1mxPBLuO2D7DwivosAekTBx
      4bJi/iNC3Ihr4HOjfYehLgon2HM8Y/taeKIsqzYnnj/Tmd6uCUOf/PwEAnGN/BS0i++1ky3iGQDHJmU9J1
      R4caNo8ahpco3Ac20b1Jr5qJgRVqs1kKQ3Q3O9UaVtIxepli1G/qWqrUtkSzdSPDblYdH0szWNH8Goyzdu
      BFnPiIQD9ZlNs2JTiYDjRm8eLVIErJUHXSIXn5jNEqooz1vuBvxxSkfPP8Uq3TNM7Ner1HrVZtY28QB2Fw
      ayzcV4pabLgVnBum78Z9a7XWPFQjaYj3NwCKYXlP1OZSpfPvFQjm/5WdCs1vW/omb1zC8LYbsHdXI/97x6
      IsP8pbZy1dU8yjyeQI3eI1x2PK8uYcDEjapxv/HzvTjBQO/6rwkjuF1cIJVW0A5PsEwoiYO0jXvwg+EZCV
      ziCihNnixG2BP6oP1dd09QZywBjtUm6iZZAhJYDIp18CzSgX1boMhPgRkO13HLzLMmyTwBDgSK43VQ4Pxd
      MOli3sO0Bq1vTPFMHIDjAWEghoioyhFNgmXBLYb1QbyuthNevAJTs5vZx2ztXHJ92z+eN193YA1v6WPCVm
      NvOaPaLi/T2BTg/jzFeDkeUd8nA=
