# Copyright (c) 2015 The Regents of the University of Michigan.
# All Rights Reserved.
# Licensed according to the terms of the Revised BSD License
# See LICENSE.md for details.

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: >
    2ea1fbd4ac4699fd0e31096b51ef545b482d9ad4bd40ca7a07276a6712e45dcc
    b821a88bc2adc09793b0ddc2be19e16068c48286ab659aad7807a8e5c1b32c3a

test:
  secret_key_base:
    525e7a0e528c0972699d038ef6a5eb35c493cd6db6db85baf0bf756ba59aeb50
    a2f5bd38b421d61cc99683df3da779048ec615a5fd72e62c65a86f3f71edcc25

impersonate_defaults: &impersonate_defaults
  secret_key_base: >
    f605b237b5e96c365904f757b0b9dd685d871b8e631c9ab059ff12a13b07af90
    8bcb1536cb1b0621bf99d7f9e41f1843fee55f93e808d308d4064bb6330c2f2b

impersonate_aptrust:
  <<: *impersonate_defaults
  salt: impersonate_aptrust_salt
  local_namespace: aptrust
  port: 3001

impersonate_chron:
  <<: *impersonate_defaults
  salt: impersonate_chron_salt
  local_namespace: chron
  port: 3002

impersonate_hathi:
  <<: *impersonate_defaults
  salt: impersonate_hathi_salt
  local_namespace: hathi
  port: 3003

impersonate_sdr:
  <<: *impersonate_defaults
  salt: impersonate_sdr_salt
  local_namespace: sdr
  port: 3004

impersonate_tdr:
  <<: *impersonate_defaults
  salt: impersonate_tdr_salt
  local_namespace: tdr
  port: 3005




